name: fb_list_view
description: A new Flutter package project.
version: 0.0.2
author: Vicky Mohammad
homepage: https://github.com/vicmoh/fb_list_view

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  # Widget for pagination
  pull_to_refresh: ^1.5.8

  # Firebase
  firebase_auth: ^0.16.0
  firebase_database: ^3.1.1
  firebase_core: ^0.4.3+3
  firebase_messaging: ^6.0.9
  cloud_firestore: ^0.13.0+1
  firebase_storage: ^3.1.1

  flutter_test:
    sdk: flutter

  provider_skeleton:
    git:
      url: git://github.com/vicmoh/provider_skeleton.git
      ref: v0.0.11

  dart_util:
    git:
      url: git://github.com/vicmoh/dart_util.git
      ref: v0.06

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # To add assets to your package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
